### ISSUE TITLE
Bug Gauges not working

### ISSUE THREAD

**Issue by Banananaman91** [librasaur/ProjectHephaestus#19]
Gauge pop ups aren't working. Currently implementation is on the Anvil.

**Comment by Banananaman91** [comment]
Spotted issue with them not showing

https://github.com/librasaur/ProjectHephaestus/blob/460ab2cdd1aa90c7d35fe41506c34478b05777cc/ProjectHephaestus/Assets/Scripts/GaugeManager.cs#L21

**Comment by lizziebriggs** [comment]
Fixed it!
